//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxminded.Calculator.TextResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foxminded.Calculator.TextResourses.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input attempts is exhausted..
        /// </summary>
        internal static string AttemptsExhausted {
            get {
                return ResourceManager.GetString("AttemptsExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has exceeded the number of attempts to enter the file path..
        /// </summary>
        internal static string CauseOfError {
            get {
                return ResourceManager.GetString("CauseOfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Division by zero..
        /// </summary>
        internal static string DevisionByZero {
            get {
                return ResourceManager.GetString("DevisionByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results file is located at: {0}.
        /// </summary>
        internal static string FileWithResults {
            get {
                return ResourceManager.GetString("FileWithResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test5 (Calculator) v{0}, 2021
        ///Written by Dmitriy Bulynko
        ///Calculate an arithmetic expressions..
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to the file: (Press &quot;Enter&quot; to skip)
        ///.
        /// </summary>
        internal static string IntriduceToEnterThePathToFile {
            get {
                return ResourceManager.GetString("IntriduceToEnterThePathToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an expression for calculation:.
        /// </summary>
        internal static string IntroduceToEnterAnExpression {
            get {
                return ResourceManager.GetString("IntroduceToEnterAnExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is incorrect! .
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &quot;Y&quot; to calculate one more expression..
        /// </summary>
        internal static string OfferToCalculateOneMoreExpresion {
            get {
                return ResourceManager.GetString("OfferToCalculateOneMoreExpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attempts remain..
        /// </summary>
        internal static string RemainingAttempts {
            get {
                return ResourceManager.GetString("RemainingAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file path: {0}.
        /// </summary>
        internal static string SpecifiedPath {
            get {
                return ResourceManager.GetString("SpecifiedPath", resourceCulture);
            }
        }
    }
}
